spring:
  flyway:
    table: user_services_flyway_schema_history

  application:
    name: UserServices
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_SECRET_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: ${RABBITMQ_DEFAULT_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

    listener:
      simple:
        acknowledge-mode: manual
    queues:
      user-block-queue:
        arguments:
          x-dead-letter-exchange: dead-letter-exchange
          x-dead-letter-routing-key: dead-letter-routing-key


  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: 0

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  public:
    key: file:${RSA_PUBLIC_KEY}
  private:
    key: file:${RSA_PRIVATE_KEY}

gcp:
  credentials:
    file: ${GOOGLE_CLOUD_CREDENTIALS}
  project-id: ${GOOGLE_CLOUD_PROJECT}
  bucket: ${GOOGLE_CLOUD_BUCKET}

app:
  image:
    upload-dir: ${IMAGE_FILE_DIR}

springdoc:
  api-docs:
    path: /api/user/docs/api-docs
  swagger-ui:
    path: /api/user/docs/
    config-url: /api/user/docs/api-docs/swagger-config
    urls:
      - name: users-service
        url: /api/user/docs/api-docs
