spring:
  application:
    name: UserServices
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_MAIL_ADDRESS}
    password: ${APP_MAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: 0

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  public:
    key: file:${PBKEY_PATH}
  private:
    key: file:${PVKEY_PATH}
app:
  image:
    upload-dir: ${IMG_FILE_DIR}
