spring:
  application:
    name: UserServices
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_EMAIL_ADDRESS}
    password: ${APP_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  public:
    key: file:${FILE_PUBKEY}
  private:
    key: file:${FILE_PRIVKEY}
app:
  image:
    upload-dir: ${IMAGES_UPLOADIR_PATH}
