release-tag-on-git:
  stage: release-tag
  needs:
    - run-unit-tests
  script:
    - TIMESTAMP=$(($(date +%s%N)/1000000))
    - VERSION="1.${CI_PIPELINE_IID}.${TIMESTAMP}"
    - git config --global user.email "${GITLAB_EMAIL}"
    - git config --global user.name "${GITLAB_NAME}"
    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@gitlab.com/velo-company/services/users-service.git
    - git tag "$VERSION"
    - git push origin "$VERSION"
#  only:
#    - main
  tags:
    - sao-caetano-matrix